# Generated by scripts/make-formula.sh in prime-radiant-inc/ledger — edit there.
class Chit < Formula
  desc "Durable, git-backed working-state for coding agents"
  homepage "https://github.com/prime-radiant-inc/ledger"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.3.0/chit-darwin-arm64.tar.gz"
      sha256 "2fee9322b21581004fb0fd3b4d0a868988b1999fcb5a53b13af58b2e3dff5339"
    else
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.3.0/chit-darwin-amd64.tar.gz"
      sha256 "b447c25cd22805f62eedf1e3e879565a306d575d378666d17d2883dad7ae4b3b"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.3.0/chit-linux-arm64.tar.gz"
      sha256 "720bfebfec605d446a95830c20e478f473dc43db0b13cc017e1513ff7b04214d"
    else
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.3.0/chit-linux-amd64.tar.gz"
      sha256 "cefffb6fee815eaf8954144a649641da2530d770d609429d709c0659263e4720"
    end
  end

  def install
    bin.install "chit"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chit version")
  end
end
