# Generated by scripts/make-formula.sh in prime-radiant-inc/ledger — edit there.
class Ledger < Formula
  desc "Durable, git-backed working-state for coding agents"
  homepage "https://github.com/prime-radiant-inc/ledger"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.1.0/ledger-darwin-arm64.tar.gz"
      sha256 "ed59c75820cf964b7b4f8e943ad90548ecfd02605fdf696a6a59621eac8fea82"
    else
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.1.0/ledger-darwin-amd64.tar.gz"
      sha256 "f446eca782d4cba5fc3caeff05ec525e35fabdec3357e26cad22b62f1ab70796"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.1.0/ledger-linux-arm64.tar.gz"
      sha256 "577e1eb253ffdb93507306178a195cd79fa76ac23d827eb640b6c63312b6ab7e"
    else
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.1.0/ledger-linux-amd64.tar.gz"
      sha256 "43aa8553dc270b12fd2cc9cf80992397e7cea05e4bbfe3d1be2612bc99255158"
    end
  end

  def install
    bin.install "ledger"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ledger version")
  end
end
