# Generated by scripts/make-formula.sh in prime-radiant-inc/ledger — edit there.
class Ledger < Formula
  desc "Durable, git-backed working-state for coding agents"
  homepage "https://github.com/prime-radiant-inc/ledger"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.2.0/ledger-darwin-arm64.tar.gz"
      sha256 "71d05fa11bb0ce7f9e14b73dda929de3197eefc8351861d3b19374400678fae7"
    else
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.2.0/ledger-darwin-amd64.tar.gz"
      sha256 "fb60f3a234e91d50c7d72e7467fef8e934919c9893baa1f7c690cc378488b0f8"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.2.0/ledger-linux-arm64.tar.gz"
      sha256 "5ae6845b1561ace969eb7a37acc56bf5dbea1bb19e6e926451835dcf01ff605f"
    else
      url "https://github.com/prime-radiant-inc/ledger/releases/download/v0.2.0/ledger-linux-amd64.tar.gz"
      sha256 "696fbe796509a4d7d1cdba4491bdffe9a366cb6538dbde07297bd129355d74d3"
    end
  end

  def install
    bin.install "ledger"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ledger version")
  end
end
